default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gaga_test_dev

test:
  <<: *default
  database: gaga_test_test

production:
  <<: *default
  database: gaga_test
